{{- $replicaCount := int .Values.replicaCount }}
{{- if and .Values.pdb.enabled (or (gt $replicaCount 1) .Values.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spartan.fullname" . }}
  labels:
    {{- include "spartan.labels" . | nindent 4}}
    tier: "pdb"
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "spartan.selectorLabels" . | nindent 6 }}
{{- end }}
