{{- if .Values.secret.asFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spartan.secretAsFile" . }}
  labels:
    {{- include "spartan.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret.asFile.data | nindent 2 }}
type: Opaque
{{- end }}
---
{{- if .Values.secret.asEnv.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spartan.secretAsEnv" . }}
  labels:
    {{- include "spartan.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret.asEnv.data | nindent 2 }}
type: Opaque
{{- end }}
