{{- if .Values.secret.asFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chargefuze.secretAsFile" . }}
  labels:
    {{- include "chargefuze.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret.asFile.data | nindent 2 }}
type: Opaque
{{- end }}
---
{{- if .Values.secret.asEnv.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chargefuze.secretAsEnv" . }}
  labels:
    {{- include "chargefuze.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret.asEnv.data | nindent 2 }}
type: Opaque
{{- end }}
