apiVersion: v1
kind: Service
metadata:
  name: {{ include "chargefuze.fullname" . }}
  labels:
    {{- include "chargefuze.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.containerPort | default 80 }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "chargefuze.selectorLabels" . | nindent 4 }}
