name: Create Patch Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Bump version
        run: |
          git config user.email github-actions@spartan.com
          git config user.name github-actions
          ./tools/create_release.sh patch
