name: Release Charts

on: 
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          
      - name: Bump Chart Version
        run: |
          ./tool/ci.sh