name: Sync repo

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Update git configuration
        run: |
          git config user.email github-actions@spartan.com
          git config user.name github-actions

      - name: Sync repo
        run: |
          ./tools/sync_repo.sh ${{ secrets.PAT }}
